version: "3.7"

services:
  nginx:
    image: nginx
    restart: always
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d

  web:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
